### PR TITLE
Revamp repository to accommodate version update

### PR DESCRIPTION
**Pull request by tlylt**
- add .gitignore
- remove the built site from git
- adjust version
- update Netlify config
- fix typos

Proposed commit message
```
Revamp repository to accommodate version update
```

P.S. Having a bit of a problem testing the deploy to netlify button, will follow up with a fix if issues occur

### CODE REVIEW

**Review by yucheng11122017 — APPROVED** [review]
LGTM! 
I'm not sure but is there a problem with the deployment because the link deploys the repo from the Markbind/init-typical-netlify repo? 
Also is there a need to update the documents in the user guide for deploying to netlify? Eg. Adding the serve command to have ````markbind serve your_site```

**Comment by tlylt** [comment]
> I'm not sure but is there a problem with the deployment because the link deploys the repo from the Markbind/init-typical-netlify repo?

Are you referring to the Netlify deploy button link? I believe that's how it's use such that this repo can act as a template. There's a problem trying to click on the link now and it won't work because this PR has not been merged yet, so the netlify setup is not updated.

> Also is there a need to update the documents in the user guide for deploying to netlify? Eg. Adding the serve command to have ````markbind serve your_site```

Are you referring to this [section](https://markbind.org/userGuide/deployingTheSite.html#deploying-to-netlify)? The `markbind serve your_site` command in `package.json` is added so that users can serve the site locally, it's not relevant or used in netlify deployment.

**Comment by yucheng11122017** [comment]
Oh I see! Thank you for explaining it to me

**Review by ong6 — APPROVED** [review]
LGTM

**Review by ong6 — APPROVED** [review]

**Pull request merged**
